[package]
name = "bimble"
version = "0.1.0"
edition = "2021"

[dependencies]
indicatif = "0.17.8"


[profile.release]
lto = true
opt-level = "s"
debug = false
strip = true
debug-assertions = false
overflow-checks = false
panic = "abort"

