unstable_features = true
indent_style = "Block"
reorder_imports = true
array_width = 60  
attr_fn_like_width = 60 
binop_separator = "Back"  
blank_lines_lower_bound = 1
blank_lines_upper_bound = 2
brace_style = "AlwaysNextLine"
comment_width = 80  
wrap_comments = true  
condense_wildcard_suffixes = true  
control_brace_style = "AlwaysNextLine"  
empty_item_single_line = true  
fn_params_layout = "Vertical"  
fn_call_width = 80  
fn_single_line = false  
force_multiline_blocks = true  
format_strings = true  
hard_tabs = false  
imports_layout = "HorizontalVertical"  
max_width = 100  
normalize_doc_attributes = true
normalize_comments = true  
struct_lit_width = 60  
edition = "2021"  
use_small_heuristics = "Max" 
format_code_in_doc_comments = true 