[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C", "target-feature=+crt-static",
    "-C", "link-args=-static"
]

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
rustflags = [
    "-C", "link-args=-static-libgcc -static-libstdc++"
]

[target.x86_64-apple-darwin]
linker = "clang"
rustflags = [
    "-C", "target-feature=+crt-static",
    "-C", "link-args=-static-libgcc -static-libstdc++"
]
